### ISSUE TITLE
Intercom integration 

### ISSUE THREAD

**Issue by madeius** [murcul/www.murcul.com#11]
@ziahamza 

Following code needs to be added to Murcul website for Intercom. Copy and paste before the "body" tag: 

<script>
  window.intercomSettings = {
    app_id: "puz96wbf"
  };
</script>
<script>(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',intercomSettings);}else{var d=document;var i=function(){i.c(arguments)};i.q=[];i.c=function(args){i.q.push(args)};w.Intercom=i;function l(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/puz96wbf';var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s,x);}if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})()</script>

**Comment by sirvar** [comment]
Fixed in #13
